// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZydnGzghn7tbBMeA9GHH-PJKHD2BDsHo',
    appId: '1:278832497171:web:e63969ea7fc6d6724ab5e6',
    messagingSenderId: '278832497171',
    projectId: 'tiktok-25428',
    authDomain: 'tiktok-25428.firebaseapp.com',
    storageBucket: 'tiktok-25428.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiIaCG_QVNmLcOH-EDcqix6Hq_N5geg38',
    appId: '1:278832497171:android:e38491a46ef0ddfd4ab5e6',
    messagingSenderId: '278832497171',
    projectId: 'tiktok-25428',
    storageBucket: 'tiktok-25428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6LC_siCbyDcs5vpjUGuqmIOl_HR-DoyI',
    appId: '1:278832497171:ios:361e0b5f7716631b4ab5e6',
    messagingSenderId: '278832497171',
    projectId: 'tiktok-25428',
    storageBucket: 'tiktok-25428.appspot.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6LC_siCbyDcs5vpjUGuqmIOl_HR-DoyI',
    appId: '1:278832497171:ios:4fc83a3eda72f77e4ab5e6',
    messagingSenderId: '278832497171',
    projectId: 'tiktok-25428',
    storageBucket: 'tiktok-25428.appspot.com',
    iosBundleId: 'com.example.tiktok.RunnerTests',
  );
}
